test:
  dir: db/redis/test
  port: 6381
  redis_bin: /usr/local/bin/redis-server

development:
  dir: db/redis/development
  port: 6380
  redis_bin: /usr/local/bin/redis-server

production:
  dir: db/redis/production
  port: 6380
  redis_bin: /usr/local/bin/redis-server


